import { createFileRoute } from "@tanstack/react-router";
import { demoDimensionedCadModel, renderCadSvg } from "~/cad";
import { accurateCadUnlocked, paymentLink } from "~/cad-access";
import { sql } from "~/db";
import { ensureSchema } from "~/project-schema";

export const Route = createFileRoute("/cad-demo")({ server: { handlers: { GET: async ({ request }) => {
  const projectId = new URL(request.url).searchParams.get("projectId") || "17";
  const unlocked = process.env.DATABASE_URL ? await accurateCadUnlocked(projectId).catch(() => false) : false;
  let requested = false;
  if (process.env.DATABASE_URL && /^\d+$/.test(projectId)) { await ensureSchema().catch(() => {}); const rows = await sql()`SELECT value FROM facts WHERE project_id=${projectId} AND category='cad' AND key='cad_quote_requested' ORDER BY id DESC LIMIT 1`.catch(() => []); requested = String(rows[0]?.value ?? '').toLowerCase() === 'true'; }
  const pay = paymentLink(); const svg = renderCadSvg(demoDimensionedCadModel());
  const state = unlocked ? `<p><strong>Accurate CAD unlocked.</strong> The quoted amount has been paid and the owner has released the files.</p><p><a href="/api/cad?projectId=${encodeURIComponent(projectId)}&format=svg">View Accurate CAD SVG</a> <a download href="/api/cad?projectId=${encodeURIComponent(projectId)}">Download Accurate CAD DXF</a></p>` : requested ? `<p><strong>Quote requested.</strong> We will come back with a price for your project based on its complexity.</p>` : `<p><strong>Locked — Accurate CAD is a quoted add-on.</strong> The free report already includes the schematic. Request a quote after reviewing it; pricing depends on your documents and scope.</p>${pay ? `<p><a href="${pay}">Existing payment link</a></p>` : ''}<form id="quote" style="display:grid;gap:.55rem;max-width:560px"><input name="projectId" value="${projectId}" hidden><label>Name *<input required name="name" autocomplete="name"></label><label>Email *<input required type="email" name="email" autocomplete="email"></label><fieldset><legend>Documents held</legend><label><input type="checkbox" name="docs" value="lease"> Lease</label><label><input type="checkbox" name="docs" value="floor plan"> Floor plan</label><label><input type="checkbox" name="docs" value="building regs"> Building regs</label><label><input type="checkbox" name="docs" value="none"> None</label></fieldset><label>Site visit / measured survey possible?<select name="surveyVisit"><option value="unsure">Unsure</option><option value="yes">Yes</option><option value="no">No</option></select></label><label>Requirements note<textarea name="notes" maxlength="2000" rows="4"></textarea></label><button type="submit">Request a quote for Accurate CAD</button><span id="quoteStatus" role="status"></span></form>`;
  const html = `<!doctype html><title>ATLAS AI CAD tiers</title><style>body{font:16px system-ui;max-width:1000px;margin:2rem auto;color:#172033;padding:0 1rem}svg{width:100%;border:1px solid #ccd6df;background:#fff}a,button{display:inline-block;padding:.7rem 1rem;background:#172033;color:white;text-decoration:none;border:0;border-radius:5px;margin:.25rem}.tier{border:1px solid #ccd6df;padding:1rem;margin:1rem 0;border-radius:8px}input,select,textarea{display:block;width:100%;box-sizing:border-box;padding:.5rem;margin-top:.25rem}fieldset label{display:inline-block;margin-right:1rem}</style><h1>ATLAS AI CAD tiers</h1><div class="tier"><h2>Standard — schematic</h2><p><strong>Estimated, not a survey.</strong> Free concept geometry for feasibility and design development.</p>${svg}</div><div class="tier"><h2>Accurate CAD — quoted add-on</h2>${state}<p>Source: client dimensioned documents or professional surveyor figures. ATLAS AI does not claim to provide a measured survey.</p></div><script>const f=document.querySelector('#quote');if(f)f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f);const b={projectId:d.get('projectId'),name:d.get('name'),email:d.get('email'),docs:d.getAll('docs'),surveyVisit:d.get('surveyVisit'),notes:d.get('notes')};const r=await fetch('/api/cad-quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const j=await r.json();document.querySelector('#quoteStatus').textContent=j.error||'Quote requested — refreshing…';if(r.ok)setTimeout(()=>location.reload(),500)}</script>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
} } } });
