/** Accurate CAD Phase 1: canonical dimensioned model, validation and renderers. */
export const DISCLAIMER = "This drawing is an automated CAD transcription/interpretation of the client-supplied documents or professional surveyor data identified in the title block. ATLAS AI did not carry out a measured survey and does not warrant the completeness, accuracy, scale or current condition of the source information. It is for feasibility and design-development purposes only, not for construction, setting-out, statutory approval, building-control submission, party-wall matters or reliance by contractors. Verify all critical dimensions and site conditions with a suitably qualified professional before use.";
export type Point={x:number;y:number}; export type Polygon=Point[];
export type SourceType="client_document"|"surveyor";
export interface Wall { id:string; geometry:"faces"|"centreline"; points:Polygon; thicknessMm?:number; sourceRefs:string[] }
export interface Opening { id:string; type:"door"|"window"|"glazing"|"shopfront"; position:Point; widthMm:number; wallId:string; swing?:"left"|"right"|"none"; sourceRefs:string[] }
export interface Room { id:string; label:string; polygon:Polygon; areaM2:number; sourceRefs:string[] }
export type DimensionType="overall"|"chain"|"opening"|"level"|"height";
export interface Dimension { id:string; valueMm:number; a:Point; b:Point; type:DimensionType; sourceRefs:string[] }
export interface Level { id:string; fflMm?:number; floorToCeilingMm?:number; thresholdMm?:number; sourceRefs:string[] }
export interface ShopfrontElevation { widthMm:number; heightMm:number; door?:{widthMm:number;heightMm:number;offsetMm?:number}; glazing?:{widthMm:number;heightMm:number;offsetMm?:number}[]; sillMm?:number; headMm?:number; transomMm?:number; mullionMm?:number; orientation?:string; sourceRefs:string[] }
export interface Provenance { sourceType:SourceType; sourceRefs:string[]; declaredAccuracy?:string; toleranceMm?:number; confidence:number; unresolvedDiscrepancies:string[] }
export interface TitleBlock { sourceType:SourceType; revision:string; generatedAt:string; disclaimer:string }
export interface DimensionedCadModel { units:"mm"; walls:Wall[]; openings:Opening[]; rooms:Room[]; dimensions:Dimension[]; levels:Level[]; shopfront?:ShopfrontElevation; provenance:Provenance; titleBlock:TitleBlock }
export interface Validation { valid:boolean; issues:string[]; notSupplied:string[] }
const area=(p:Polygon)=>Math.abs(p.reduce((s,q,i)=>s+q.x*p[(i+1)%p.length].y-q.y*p[(i+1)%p.length].x,0))/2/1e6;
const closed=(p:Polygon)=>p.length>2&&p[0].x===p[p.length-1].x&&p[0].y===p[p.length-1].y;
export function validateCadModel(m:DimensionedCadModel):Validation { const issues:string[]=[], notSupplied:string[]=[]; for(const w of m.walls)if(!closed(w.points))issues.push(`unclosed perimeter: wall ${w.id}`); for(const r of m.rooms)if(!closed(r.polygon))issues.push(`unclosed perimeter: room ${r.id}`); const chains=m.dimensions.filter(d=>d.type==="chain"); const overall=m.dimensions.filter(d=>d.type==="overall"); if(chains.length&&overall.length){const sum=chains.reduce((s,d)=>s+d.valueMm,0);if(Math.abs(sum-overall[0].valueMm)>1)issues.push("dimension chain contradiction")} if(!m.levels.length)notSupplied.push("levels"); if(!m.shopfront)notSupplied.push("shopfront elevation"); if(!m.provenance.declaredAccuracy)notSupplied.push("declared accuracy/tolerance"); return {valid:issues.length===0,issues,notSupplied}; }
function n(v:number){return Number.isFinite(v)?Math.round(v*100)/100:0} function esc(s:string){return s.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]!))}
const layers=["WALLS","OPENINGS","DIMENSIONS","TEXT","FIXTURES","LEVELS","SHOPFRONT","TITLE_BLOCK"];
export function renderDxf(m:DimensionedCadModel):string { const out:string[]=["0","SECTION","2","HEADER","9","$ACADVER","1","AC1009","9","$INSUNITS","70","4","0","ENDSEC","0","SECTION","2","TABLES","0","TABLE","2","LAYER","70",String(layers.length)]; for(const l of layers)out.push("0","LAYER","2",l,"70","0","62","7","6","CONTINUOUS"); out.push("0","ENDTAB","0","ENDSEC","0","SECTION","2","ENTITIES"); const line=(a:Point,b:Point,l:string)=>out.push("0","LINE","8",l,"10",String(n(a.x)),"20",String(n(a.y)),"30","0","11",String(n(b.x)),"21",String(n(b.y)),"31","0"); const poly=(p:Polygon,l:string)=>{for(let i=1;i<p.length;i++)line(p[i-1],p[i],l)}; for(const w of m.walls)poly(w.points,"WALLS"); for(const r of m.rooms)poly(r.polygon,"WALLS"); for(const o of m.openings){line(o.position,{x:o.position.x+o.widthMm,y:o.position.y},"OPENINGS");} for(const d of m.dimensions){line(d.a,d.b,"DIMENSIONS"); out.push("0","TEXT","8","TEXT","10",String(n((d.a.x+d.b.x)/2)),"20",String(n((d.a.y+d.b.y)/2)),"40","80","1",`${n(d.valueMm)} mm`)} for(const r of m.rooms)out.push("0","TEXT","8","TEXT","10",String(n(r.polygon[0]?.x||0)),"20",String(n(r.polygon[0]?.y||0)),"40","100","1",`${r.label} ${n(r.areaM2)} m2`); out.push("0","TEXT","8","TITLE_BLOCK","10","0","20","-500","40","100","1",`ATLAS AI | ${m.titleBlock.sourceType} | Rev ${m.titleBlock.revision}`,"0","TEXT","8","TITLE_BLOCK","10","0","20","-650","40","60","1",`Dimensions: ${m.provenance.sourceRefs.join(", ") || "not supplied"} | ${m.provenance.declaredAccuracy || "accuracy not supplied"} | ${m.titleBlock.generatedAt}`); out.push("0","TEXT","8","TITLE_BLOCK","10","0","20","-800","40","45","1",m.titleBlock.disclaimer,"0","ENDSEC","0","EOF"); return out.join("\n")+"\n"; }
export function renderCadSvg(m:DimensionedCadModel):string { const pts=[...m.walls.flatMap(w=>w.points),...m.rooms.flatMap(r=>r.polygon)]; const maxX=Math.max(1,...pts.map(p=>p.x)),maxY=Math.max(1,...pts.map(p=>p.y)); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${maxX/10+500} ${maxY/10+500}" role="img"><style>line,polyline{stroke:#172033;stroke-width:8;fill:none}.room{fill:#e8f0f7;stroke:#172033;stroke-width:8}.dim{stroke:#c45b32;stroke-width:4}.label{font:28px sans-serif;fill:#172033}</style>${m.rooms.map(r=>`<polygon class="room" points="${r.polygon.map(p=>`${p.x/10},${(maxY-p.y)/10}`).join(" ")}"/><text class="label" x="${r.polygon[0].x/10}" y="${(maxY-r.polygon[0].y)/10}">${esc(r.label)} ${n(r.areaM2)} m²</text>`).join("")}${m.walls.map(w=>`<polyline points="${w.points.map(p=>`${p.x/10},${(maxY-p.y)/10}`).join(" ")}"/>`).join("")}${m.dimensions.map(d=>`<line class="dim" x1="${d.a.x/10}" y1="${(maxY-d.a.y)/10}" x2="${d.b.x/10}" y2="${(maxY-d.b.y)/10}"/><text class="label" x="${(d.a.x+d.b.x)/20}" y="${(maxY-(d.a.y+d.b.y)/2)/10}">${d.valueMm} mm</text>`).join("")}<text class="label" x="20" y="${maxY/10+100}">ATLAS AI • ${m.titleBlock.sourceType} • Rev ${m.titleBlock.revision}</text><text class="label" x="20" y="${maxY/10+140}">${esc(`Dimensions: ${m.provenance.sourceRefs.join(", ") || "not supplied"} | ${m.provenance.declaredAccuracy || "accuracy not supplied"} | ${m.titleBlock.generatedAt}`)}</text><text class="label" x="20" y="${maxY/10+180}">${esc(m.titleBlock.disclaimer)}</text></svg>`; }
export interface SpaceFact { label?:string; name?:string; widthMm?:number;width?:number; lengthMm?:number;length?:number; unit?:"mm"|"m"; areaM2?:number; sourceRefs?:string[] }
export function buildCadModel(facts:SpaceFact[], survey?:Partial<DimensionedCadModel>):DimensionedCadModel { const rooms=facts.map((f,i)=>{const scale=f.unit==="m"?1000:1,w=Number(f.widthMm??f.width??0)*scale,l=Number(f.lengthMm??f.length??0)*scale,x=i*(w+500); return {id:`room-${i+1}`,label:f.label??f.name??"not supplied",polygon:[{x,y:0},{x:x+w,y:0},{x:x+w,y:l},{x,y:l},{x,y:0}],areaM2:area([{x,y:0},{x:x+w,y:0},{x:x+w,y:l},{x,y:l},{x,y:0}]),sourceRefs:f.sourceRefs??[]}}); const sourceType=survey?.provenance?.sourceType??"client_document"; return {units:"mm",walls:survey?.walls??[],openings:survey?.openings??[],rooms:survey?.rooms??rooms,dimensions:survey?.dimensions??[],levels:survey?.levels??[],shopfront:survey?.shopfront,provenance:survey?.provenance??{sourceType,sourceRefs:[],confidence:0,unresolvedDiscrepancies:[]},titleBlock:survey?.titleBlock??{sourceType,revision:"not supplied",generatedAt:new Date().toISOString(),disclaimer:DISCLAIMER}}; }
export function demoDimensionedCadModel():DimensionedCadModel { const p=[{x:0,y:0},{x:8000,y:0},{x:8000,y:5000},{x:0,y:5000},{x:0,y:0}]; return {units:"mm",walls:[{id:"perimeter",geometry:"faces",points:p,thicknessMm:300,sourceRefs:["demo"]}],openings:[{id:"front-door",type:"door",position:{x:1000,y:0},widthMm:1000,wallId:"perimeter",swing:"left",sourceRefs:["demo"]},{id:"front-glazing",type:"glazing",position:{x:2200,y:0},widthMm:4200,wallId:"perimeter",sourceRefs:["demo"]}],rooms:[{id:"unit",label:"Ground-floor unit",polygon:p,areaM2:40,sourceRefs:["demo"]}],dimensions:[{id:"overall-width",valueMm:8000,a:{x:0,y:-400},b:{x:8000,y:-400},type:"overall",sourceRefs:["demo"]},{id:"overall-depth",valueMm:5000,a:{x:8400,y:0},b:{x:8400,y:5000},type:"overall",sourceRefs:["demo"]}],levels:[{id:"ground",fflMm:0,floorToCeilingMm:3000,thresholdMm:0,sourceRefs:["demo"]}],shopfront:{widthMm:8000,heightMm:3000,door:{widthMm:1000,heightMm:2100,offsetMm:1000},glazing:[{widthMm:4200,heightMm:2200,offsetMm:2200}],sillMm:800,headMm:3000,orientation:"south",sourceRefs:["demo"]},provenance:{sourceType:"client_document",sourceRefs:["synthetic-demo"],declaredAccuracy:"synthetic",confidence:1,unresolvedDiscrepancies:[]},titleBlock:{sourceType:"client_document",revision:"DEMO",generatedAt:new Date().toISOString(),disclaimer:DISCLAIMER}}; }
